
export const textConfig: Record<string, string[]> = {
  "nav_spatial": ["Apzumi Spatial", "Spatial Solutions", "AR/VR Platforms"],
  "nav_services": ["Usługi", "Oferta", "Rozwiązania", "Co robimy"],
  "nav_cases": ["Case Studies", "Realizacje", "Nasi Klienci", "Historie Sukcesu"],
  "nav_about": ["O Nas", "Zespół", "Firma", "Kim jesteśmy"],
  "nav_contact": ["Porozmawiajmy", "Kontakt", "Napisz do nas", "Umów spotkanie"],
  "nav_lang_pl": ["PL", "Polski", "Polska"],
  "nav_lang_en": ["EN", "English", "Angielski"],
  "hero_title": ["Apzumi Spatial — Twój partner w procesach przemysłowych", "Apzumi Spatial — Nowy wymiar produkcji", "Apzumi Spatial — Cyfrowa transformacja IT/OT"],
  "hero_lead": ["Łączymy ludzi, procedury i wiedzę w jednym workflow.", "Tworzymy cyfrowe środowisko pracy dla przemysłu 4.0.", "Wspieramy Twoje procesy nowoczesną technologią AR i AI."],
  "hero_cta": ["Poznaj platformę Apzumi Spatial", "Zobacz jak działamy", "Rozpocznij transformację", "Skontaktuj się z nami"],
  "cs_hero_title": ["Case Studies — Apzumi Spatial w akcji", "Nasze Realizacje", "Wdrożenia Przemysł 4.0"],
  "cs_hero_lead": ["Zobacz, jak łączymy ludzi, procedury i wiedzę w jednym workflow — w realnych projektach na produkcji, w serwisie i w logistyce.", "Zobacz, jak łączymy ludzi, procedury i wiedzę w jednym workflow.", "Sprawdź, jak łączymy ludzi, instrukcje i wiedzę operacyjną w jednym środowisku pracy — w realnych projektach na hali, w serwisie i w logistyce."],
  "cs_hero_cta_primary": ["Porozmawiajmy", "Skontaktuj się", "Umów spotkanie"],
  "cs_hero_cta_secondary": ["Zobacz rozwiązania", "Zobacz rozwiązania", "Zobacz rozwiązania"],
  "cs_proof_label": ["Zaufali nam liderzy:", "Wdrożenia w:", "Klienci:"],
  "cs_filter_search_ph": ["Szukaj po firmie, problemie lub technologii...", "Szukaj po firmie, problemie lub technologii...", "Szukaj po firmie, problemie lub technologii..."],
  "cs_filter_area": ["Obszar", "Dział", "Zakres"],
  "cs_filter_tech": ["Technologia", "Narzędzie", "Podejście"],
  "cs_filter_industry": ["Branża", "Sektor", "Przemysł"],
  "cs_sort_label": ["Sortuj:", "Kolejność:", "Pokaż:"],
  "cs_kan_client": ["KAN", "KAN", "KAN"],
  "cs_kan_title": ["Optymalizacja pracy operatorów w KAN", "Optymalizacja pracy operatorów w KAN", "Optymalizacja pracy operatorów w KAN"],
  "cs_kan_desc": ["KAN wykorzystał Apzumi Spatial, aby ustandaryzować i zdigitalizować procedury serwisowe oraz usprawnić komunikację z serwisem. Rozwiązanie działa na smart okularach (HoloLens 2) i wspiera szkolenia, raportowanie oraz pracę w trybie ‘paperless’.", "KAN wykorzystał Apzumi Spatial, aby ustandaryzować i zdigitalizować procedury serwisowe oraz usprawnić komunikację z serwisem.", "KAN wykorzystał Apzumi Spatial, aby ustandaryzować i zdigitalizować instrukcje serwisowe oraz usprawnić komunikację z serwisem. Rozwiązanie działa na smart okularach (HoloLens 2) i wspiera szkolenia, raportowanie oraz pracę w trybie ‘paperless’."],
  "cs_kan_res_1": ["Poprawa efektywności procesów serwisowych", "Poprawa efektywności procesów serwisowych", "Poprawa efektywności procesów serwisowych"],
  "cs_kan_res_2": ["Redukcja błędów wykonywanych przez pracowników", "Redukcja błędów wykonywanych przez pracowników", "Redukcja błędów wykonywanych przez pracowników"],
  "cs_kan_res_3": ["Standaryzacja przepływu i lepsze wykorzystanie kompetencji", "Standaryzacja przepływu i lepsze wykorzystanie kompetencji", "Standaryzacja przepływu i lepsze wykorzystanie kompetencji"],
  "cs_kan_res_4": ["Poprawa ergonomii i bezpieczeństwa pracy", "Poprawa ergonomii i bezpieczeństwa pracy", "Poprawa ergonomii i bezpieczeństwa pracy"],
  "cs_kan_res_5": ["Zmniejszenie kosztów serwisów (delegacje) i strategia ‘paperless’", "Zmniejszenie kosztów serwisów (delegacje) i strategia ‘paperless’", "Zmniejszenie kosztów serwisów (delegacje) i strategia ‘paperless’"],
  "cs_kan_chal": ["Celem projektu było podniesienie efektywności prac serwisowych poprzez ustandaryzowanie i zdigitalizowanie procedur oraz analizę wykonywanych działań. Firma KAN chciała wyeliminować błędy serwisowe i skrócić czas realizacji prac. Zarząd oczekiwał narzędzia, które wyeliminuje dokumentację papierową, zapewni wizualizację zadań (zdjęcia, wideo) dla lepszego zrozumienia procesu, będzie służyć do szkolenia pracowników oraz umożliwi komunikację zdalną z zewnętrznymi serwisantami."],
  "cs_kan_sol": ["Zdecydowano się na wdrożenie dedykowanego rozwiązania Apzumi Spatial na goglach Microsoft HoloLens 2, wykorzystującego Rzeczywistość Rozszerzoną (AR). Dzięki temu ustandaryzowano i zdigitalizowano procedury serwisowe, dzieląc je na wykonawcze (do nauki i wsparcia) oraz sprawdzające (dla doświadczonych operatorów). Operatorzy widzą instrukcje i zdjęcia jako hologramy w swoim polu widzenia."],
  "cs_kan_impl": ["Wdrożono mechanizm raportowania, który pozwala sprawdzić czas realizacji, status zadań i ewentualne problemy w trybie real-time (np. zdjęcia z obszaru). Zdigitalizowany proces wspiera management w optymalizacji i przydzielaniu zasobów. Uruchomiono również funkcję 'Call', umożliwiającą zdalną współpracę i wykorzystanie wiedzy ekspertów na odległość, co przyspiesza szkolenia i poprawia komunikację."],
  "cs_kan_quote": ["Dzięki technologii Mixed Reality skróciliśmy czas onboardingu operatorów o 30% i wyeliminowaliśmy błędy w krytycznych fazach przezbrojenia maszyn."],
  "cs_kan_quote_auth": ["Dyrektor Produkcji, KAN"],

  "cs_tauron_client": ["TAURON", "TAURON", "TAURON"],
  "cs_tauron_title": ["Rozszerzona rzeczywistość jako narzędzie optymalizacji działania serwisu oraz kosztów", "Rozszerzona rzeczywistość jako narzędzie optymalizacji działania serwisu oraz kosztów", "Rozszerzona rzeczywistość jako narzędzie optymalizacji działania serwisu oraz kosztów"],
  "cs_tauron_desc": ["W elektrowni kluczowe jest utrzymanie sprawności instalacji. TAURON wdrożył dedykowane rozwiązanie AR na smart okularach, aby zastąpić papierowe instrukcje i schematy cyfrową, ustandaryzowaną wiedzą oraz usprawnić współpracę zdalną.", "W elektrowni kluczowe jest utrzymanie sprawności instalacji.", "W elektrowni kluczowe jest utrzymanie sprawności instalacji. TAURON wdrożył dedykowane rozwiązanie AR na smart okularach, aby zastąpić papierowe instrukcje i schematy cyfrową, ustandaryzowaną wiedzą oraz usprawnić współpracę zdalną."],
  "cs_tauron_res_1": ["Poprawa efektywności pracowników", "Poprawa efektywności pracowników", "Poprawa efektywności pracowników"],
  "cs_tauron_res_2": ["Lepsza standaryzacja i wykorzystanie kompetencji", "Lepsza standaryzacja i wykorzystanie kompetencji", "Lepsza standaryzacja i wykorzystanie kompetencji"],
  "cs_tauron_res_3": ["Poprawa ergonomii i bezpieczeństwa (efekt ‘wolnych rąk’)", "Poprawa ergonomii i bezpieczeństwa (efekt ‘wolnych rąk’)", "Poprawa ergonomii i bezpieczeństwa (efekt ‘wolnych rąk’)"],
  "cs_tauron_res_4": ["Wsparcie w niwelowaniu luki kompetencyjnej", "Wsparcie w niwelowaniu luki kompetencyjnej", "Wsparcie w niwelowaniu luki kompetencyjnej"],
  "cs_tauron_res_5": ["Skrócenie czasu awarii", "Skrócenie czasu awarii", "Skrócenie czasu awarii"],
  "cs_tauron_chal": ["Bardzo ważnym aspektem działania elektrowni jest utrzymanie sprawności instalacji. Tauron mierzył się z wyzwaniem zastąpienia dużej ilości papierowej dokumentacji (instrukcji, rysunków technicznych, schematów) wersją cyfrową. Kluczowym problemem była niska ergonomia pracy z papierem w terenie oraz konieczność zapewnienia efektywnej komunikacji ze zdalnymi ekspertami (szczególnie w obliczu ograniczeń w przemieszczaniu się)."],
  "cs_tauron_sol": ["Zdecydowano się na wdrożenie dedykowanego rozwiązania na okulary AR (Augmented Reality). System pozwala nakładać dodatkowe informacje (instrukcje, schematy, obrazy, hologramy) na widok rzeczywistego otoczenia. Dzięki temu pracownik ma dostęp do wybranej dokumentacji technicznej bezpośrednio przy analizowanym urządzeniu i może współdziałać z systemem bez użycia rąk."],
  "cs_tauron_impl": ["Technologia AR zapewniła efekt 'wolnych rąk', znacząco poprawiając bezpieczeństwo i ergonomię prac serwisowych. Rozwiązanie umożliwia aktywną opiekę nad instalacjami przez wysokiej klasy specjalistów poprzez zdalną asystę, niwelując bariery odległości. System wspiera również wymianę wiedzy międzypokoleniową i pomaga niwelować lukę kompetencyjną w zespołach technicznych."],
  "cs_tauron_quote": ["Technologia AR przyczyni się do poprawy efektywności pracowników, zoptymalizuje czynności oraz sprawi, że ich wiedza będzie lepiej wykorzystywana. Pozwoli również zwiększyć ergonomię prac oraz bezpieczeństwo poprzez wirtualną asystę."],
  "cs_tauron_quote_auth": ["Wojciech Przepadło, Wiceprezes Zarządu TAURON Wytwarzanie"],

  "cs_vw_client": ["Volkswagen Poznań", "Volkswagen Poznań", "Volkswagen Poznań"],
  "cs_vw_title": ["Optymalizacja powierzchni magazynowej z wykorzystaniem AR Container Planning", "Optymalizacja powierzchni magazynowej z wykorzystaniem AR Container Planning", "Optymalizacja powierzchni magazynowej z wykorzystaniem AR Container Planning"],
  "cs_vw_desc": ["Volkswagen wykorzystał AR do projektowania i testowania kontenerów specjalnych bez budowy fizycznych prototypów. Pilotaż i iteracje pozwoliły przejść do wersji produkcyjnej i zintegrować narzędzie z systemami wewnętrznymi.", "Volkswagen wykorzystał AR do projektowania i testowania kontenerów specjalnych bez budowy fizycznych prototypów.", "Volkswagen wykorzystał AR do projektowania i testowania kontenerów specjalnych bez budowy fizycznych prototypów. Pilotaż i iteracje pozwoliły przejść do wersji produkcyjnej i zintegrować narzędzie z systemami wewnętrznymi."],
  "cs_vw_res_1": ["Oszczędności w kosztach produkcji prototypów", "Oszczędności w kosztach produkcji prototypów", "Oszczędności w kosztach produkcji prototypów"],
  "cs_vw_res_2": ["Skrócenie cyklu wprowadzania nowych kontenerów", "Skrócenie cyklu wprowadzania nowych kontenerów", "Skrócenie cyklu wprowadzania nowych kontenerów"],
  "cs_vw_res_3": ["Szybsza i dokładniejsza współpraca z dostawcami", "Szybsza i dokładniejsza współpraca z dostawcami", "Szybsza i dokładniejsza współpraca z dostawcami"],
  "cs_vw_res_4": ["W pełni cyfrowy przepływ pracy", "W pełni cyfrowy przepływ pracy", "W pełni cyfrowy przepływ pracy"],
  "cs_vw_res_5": ["Mniej kosztów transportu prototypowych kontenerów", "Mniej kosztów transportu prototypowych kontenerów", "Mniej kosztów transportu prototypowych kontenerów"],
  "cs_vw_chal": ["Volkswagen Poznań potrzebował usprawnić proces projektowania i zamawiania specjalistycznych pojemników logistycznych, unikając opóźnień i optymalizując zyski. Tradycyjny proces wymagał budowy drogich, fizycznych prototypów, ich transportu i długotrwałych testów. Oczekiwano narzędzia innowacyjnego, ale praktycznego, które pozwoli projektować i testować kontenery w AR bez ich fizycznego tworzenia, unikając błędów projektowych."],
  "cs_vw_sol": ["Projekt zrealizowano w kilku etapach: od analizy możliwości AR i warsztatów, przez pilotaż na ograniczonej skali (potwierdzenie założeń, zbieranie doświadczeń), aż po kolejne iteracje usprawnień. Pozwoliło to na wypracowanie spójnej wizji i zebranie argumentów do uruchomienia produkcyjnego narzędzia 'AR Container Planning'."],
  "cs_vw_impl": ["Ostatnim krokiem była integracja aplikacji z systemami wewnętrznymi VW i wdrożenie w trybie produkcyjnym na dużą skalę. System zbiera dane o użytkowaniu i pozwala na wczesne wykrycie błędów konstrukcyjnych oraz kolizji z infrastrukturą. Wirtualny model kontenera może być sprawdzony przez planistę w dowolnym czasie przed jego fizyczną budową i transportem."],
  "cs_vw_quote": ["Wdrożenie AR Container Planning przede wszystkim oszczędza koszty transportu kontenerów prototypowych. Wirtualny model kontenera może sprawdzić planista w dowolnym ustawieniu i czasie przed ostateczną budową."],
  "cs_vw_quote_auth": ["Tomasz Rudalski, Project Manager wdrożenia w VW Września"],

  "cs_label_category": ["Kategoria:", "Obszar:", "Tagi:"],
  "cs_label_results": ["Kluczowe rezultaty:", "Efekty:", "Wyniki:"],
  "cs_btn_read": ["Czytaj case study", "Czytaj case study", "Czytaj case study"],
  "cs_btn_demo": ["Umów demo", "Umów demo", "Umów demo"],
  "cs_badge_readtime": ["3 min czytania", "5 min", "2 min"],
  "cs_proc_heading": ["Od rozpoznania do skali — w 3 prostych krokach", "Od rozpoznania do skali.", "Od rozpoznania do skali — w 3 prostych krokach"],
  "cs_proc_1_title": ["Rozpoznanie i doprecyzowanie celu", "Rozpoznanie i doprecyzowanie celu", "Rozpoznanie i doprecyzowanie celu"],
  "cs_proc_1_desc": ["KPI, mapa procesu, warsztat", "KPI, mapa procesu, warsztat", "KPI, mapa procesu, warsztat"],
  "cs_proc_2_title": ["Pilot / PoC-first", "Pilot / PoC-first", "Pilot / PoC-first"],
  "cs_proc_2_desc": ["Weryfikacja w boju i policzenie efektu", "Weryfikacja w boju i policzenie efektu", "Weryfikacja w boju i policzenie efektu"],
  "cs_proc_3_title": ["Skalowanie i utrzymanie efektu", "Skalowanie i utrzymanie efektu", "Skalowanie i utrzymanie efektu"],
  "cs_proc_3_desc": ["Monitoring, optymalizacja, rollout", "Monitoring, optymalizacja, rollout", "Monitoring, optymalizacja, rollout"],
  "cs_form_heading": ["Chcesz podobny efekt u siebie?", "Chcesz podobny efekt u siebie?", "Chcesz podobny efekt u siebie?"],
  "cs_form_desc": ["Opowiedz nam o procesie. Dobierzemy rozwiązanie Apzumi Spatial i zaproponujemy plan pilota.", "Opowiedz nam o procesie.", "Opowiedz nam o procesie. Dobierzemy rozwiązanie Apzumi Spatial i zaproponujemy plan pilota."],
  "cs_form_btn": ["Porozmawiajmy", "Porozmawiajmy", "Porozmawiajmy"],
  "cs_form_btn_sec": ["Poproś o demo", "Zobacz demo", "Umów prezentację"],
  "client_polpharma": ["polpharma", "polpharma", "polpharma"],
  "client_tauron": ["TAURON", "TAURON", "TAURON"],
  "client_volkswagen": ["Volkswagen", "Volkswagen", "Volkswagen"],
  "client_sitech": ["sitech", "sitech", "sitech"],
  "client_audi": ["AUDI", "AUDI", "AUDI"],
  "client_impel": ["Impel", "Impel Group", "Grupa Impel"],
  "process_heading": ["Nasza metodologia pracy", "Ścieżka do sukcesu Twojej firmy", "Jak wdrażamy innowacje?"],
  "process_subheading": ["Twój sukces to proces. Prowadzimy Cię od rozpoznania do skalowania — w 3 prostych krokach.", "Od audytu do wdrożenia — transparentny proces współpracy.", "Zaufaj sprawdzonej metodzie wdrażania technologii."],
  "process_step1_sub": ["KROK 1", "FAZA 1", "START"],
  "process_step1_title": ["Rozpoznanie i doprecyzowanie celu", "Definicja Wymagań", "Warsztat Wstępny"],
  "process_step1_desc": ["Mapujemy proces, potrzeby i ograniczenia. Ustalamy KPI oraz to, co ma powstać.", "Spotykamy się, aby zrozumieć specyfikę Twojego biznesu.", "Zbieramy dane niezbędne do zaprojektowania rozwiązania."],
  "process_step2_sub": ["KROK 2", "FAZA 2", "POC"],
  "process_step2_title": ["Pilot / PoC-first", "Szybki Prototyp", "Testy Pilotażowe"],
  "process_step2_desc": ["Budujemy i uruchamiamy pilota na realnym fragmencie procesu, żeby zweryfikować założenia i policzyć efekt.", "Weryfikujemy założenia w bezpiecznym środowisku testowym.", "Sprawdzamy ROI na małej skali przed pełnym wdrożeniem."],
  "process_step3_sub": ["KROK 3", "FAZA 3", "SCALE"],
  "process_step3_title": ["Skalowanie i utrzymanie efektu", "Ekspansja Systemu", "Produkcyjne Uruchomienie"],
  "process_step3_desc": ["Rozszerzamy rozwiązanie na kolejne obszary, monitorujemy wyniki i optymalizujemy.", "Integrujemy system z resztą infrastruktury IT/OT.", "Zapewniamy wsparcie i rozwój po uruchomieniu."],
  "solutions_heading": ["Wybierz usługę lub rozwiązanie dla Twojej produkcji", "Katalog usług i produktów Apzumi", "Rozwiązania skrojone na miarę przemysłu"],
  "solutions_subheading": ["Jeśli dopiero zaczynasz — wybierz usługę. Jeśli masz konkretny problem — wybierz gotowe rozwiązanie Apzumi Spatial.", "Niezależnie od etapu cyfryzacji, znajdziemy rozwiązanie dla Ciebie.", "Wybierz ścieżkę customową lub sprawdzone rozwiązania pudełkowe."],
  "solutions_section_ready": ["Gotowe rozwiązania Apzumi Spatial", "Produkty Apzumi Spatial", "Rozwiązania Pudełkowe"],
  "solutions_section_services": ["Usługi", "Wsparcie Projektowe", "Usługi Szyte na Miarę"],
  "sol_label_spatial": ["Apzumi Spatial", "Produkt", "Platforma"],
  "sol_label_who": ["DLA KOGO", "ADRESAT", "GRUPA DOCELOWA"],
  "sol_label_when": ["KIEDY WARTO", "WYZWANIA", "POTRZEBY"],
  "sol_label_what": ["CO DOSTAJESZ", "ROZWIĄZANIE", "ZAKRES"],
  "sol_label_effect": ["EFEKT", "KORZYŚCI", "ROI"],
  "sol_label_diff": ["Nasz wyróżnik:", "Dlaczego my?", "Unikalna wartość"],
  "sol_more": ["Dowiedz się więcej", "Szczegóły", "Czytaj dalej"],
  "sol_title_1": ["AI Workshop", "Warsztaty Strategiczne AI", "Konsultacje Przemysł 4.0"],
  "sol_1_forWho": ["Średnie firmy produkcyjne, logistyka i retail. Liderzy operacji, transformacji i IT.", "Średnie firmy produkcyjne, logistyka i retail.", "Średnie firmy produkcyjne, logistyka i retail. Liderzy operacji, transformacji i IT."],
  "sol_1_when": ["Czujesz presję na automatyzację/AI, ale nie wiesz od czego zacząć i co da ROI.", "Czujesz presję na automatyzację/AI.", "Czujesz presję na automatyzację/AI, ale nie wiesz od czego zacząć i co da ROI."],
  "sol_1_what": ["Mapa potrzeb i priorytetów, lista use-case’ów, rekomendacje danych i integracji, wstępna roadmapa.", "Mapa potrzeb i priorytetów.", "Mapa potrzeb i priorytetów, lista use-case’ów, rekomendacje danych i integracji, wstępna roadmapa."],
  "sol_1_effect": ["Szybka decyzja co ma sens, mniej ryzyka, jasny plan kolejnych kroków.", "Szybka decyzja co ma sens, mniej ryzyka, jasny plan kolejnych kroków.", "Szybka decyzja co ma sens, mniej ryzyka, jasny plan kolejnych kroków."],
  "sol_1_diff": ["Łączymy doświadczenie przemysłowe z praktyką dowożenia rozwiązań AI.", "Integrujemy doświadczenie przemysłowe z praktyką dowożenia rozwiązań AI.", "Spajamy doświadczenie przemysłowe z praktyką dowożenia rozwiązań AI."],
  "sol_title_2": ["AI Prototyping & Product Discovery", "Prototypowanie AI", "Proof of Concept AI"],
  "sol_2_forWho": ["Duże organizacje produkcyjne/logistyczne z zespołami IT i innowacji.", "Duże organizacje produkcyjne/logistyczne z zespołami IT i innowacji.", "Duże organizacje produkcyjne/logistyczne z zespołami IT i innowacji."],
  "sol_2_when": ["Masz pomysł na AI, ale chcesz go zweryfikować zanim zainwestujesz w pełny projekt.", "Masz pomysł na AI, ale chcesz go zweryfikować zanim zainwestujesz w pełny projekt.", "Masz pomysł na AI, ale chcesz go zweryfikować zanim zainwestujesz w pełny projekt."],
  "sol_2_what": ["Prototyp (PoC) + opis funkcji i wymagań, backlog oraz plan pilotażu.", "Prototyp (PoC) + opis funkcji i wymagań.", "Prototyp (PoC) + opis funkcji i wymagań, backlog oraz plan pilotażu."],
  "sol_2_effect": ["Walidacja wartości i użyteczności, krótszy czas do pierwszych wyników.", "Walidacja wartości i użyteczności.", "Walidacja wartości i użyteczności, krótszy czas do pierwszych wyników."],
  "sol_2_diff": ["Prototypujemy tak, by szybko potwierdzić wartość biznesową.", "Prototypujemy tak, by szybko potwierdzić wartość biznesową.", "Prototypujemy tak, by szybko potwierdzić wartość biznesową."],
  "sol_title_3": ["Digitalizacja i Custom Development", "Aplikacje Dedykowane", "Software House"],
  "sol_3_forWho": ["Duże firmy, gdy gotowe narzędzia nie pasują i potrzebne są integracje (MES/ERP).", "Duże firmy, gdy gotowe narzędzia nie pasują i potrzebne są integracje (MES/ERP).", "Duże firmy, gdy gotowe narzędzia nie pasują i potrzebne są integracje (MES/ERP)."],
  "sol_3_when": ["Masz specyficzny proces lub system, którego nie da się ‘z pudełka’ ogarnąć.", "Masz specyficzny proces lub system.", "Masz specyficzny proces lub system, którego nie da się ‘z pudełka’ ogarnąć."],
  "sol_3_what": ["Dedykowaną aplikację (web/mobile/panele), integracje i rozwiązanie dopasowane do procesu.", "Dedykowaną aplikację (web/mobile/panele).", "Dedykowaną aplikację (web/mobile/panele), integracje i rozwiązanie dopasowane do procesu."],
  "sol_3_effect": ["Dopasowanie do realiów produkcji, skalowalność i szybkie iteracje.", "Dopasowanie do realiów produkcji.", "Dopasowanie do realiów fabryce, skalowalność i szybkie iteracje."],
  "sol_3_diff": ["Podejście PoC-first: nie przepalasz budżetu zanim nie ma potwierdzenia sensu.", "Podejście PoC-first: nie przepalasz budżetu zanim nie ma potwierdzenia sensu.", "Podejście PoC-first: nie przepalasz budżetu zanim nie ma potwierdzenia sensu."],
  "sol_title_4": ["Zdigitalizowane procedury dla produkcji", "Cyfrowe Instrukcje Pracy", "Paperless Factory"],
  "sol_4_forWho": ["Średnie i duże zakłady. Produkcja, utrzymanie ruchu, liderzy zmian.", "Średnie i duże zakłady.", "Średnie i duże zakłady. Produkcja, utrzymanie ruchu, liderzy zmian."],
  "sol_4_when": ["Procedury są papierowe/rozproszone, a błędy i braki instrukcji powodują przestoje.", "Procedury są papierowe/rozproszone.", "Procedury są papierowe/rozproszone, a błędy i braki instrukcji powodują przestoje."],
  "sol_4_what": ["Instrukcje i checklisty w formie cyfrowej, dostępne na stanowisku pracy + historia użycia.", "Instrukcje i checklisty w formie cyfrowej.", "Instrukcje i checklisty w formie cyfrowej, dostępne na stanowisku pracy + historia użycia."],
  "sol_4_effect": ["Mniej błędów i przestojów, szybsze wdrożenie nowych pracowników, większa zgodność.", "Mniej błędów i przestojów, szybsze wdrożenie nowych pracowników, większa zgodność.", "Mniej błędów i przestojów, szybsze wdrożenie nowych pracowników, większa zgodność."],
  "sol_4_diff": ["Rozwiązanie projektowane pod realne warunki hali produkcyjnej.", "Rozwiązanie projektowane pod realne warunki hali produkcyjnej.", "Rozwiązanie projektowane pod realne warunki hali produkcyjnej."],
  "sol_title_5": ["Audio-wizualne wsparcie pracowników (Smart Glasses)", "Zdalny Ekspert AR", "Wsparcie Smart Glasses"],
  "sol_5_forWho": ["Utrzymanie ruchu, serwis, liderzy produkcji w zakładach rozproszonych.", "Utrzymanie ruchu, serwis, liderzy fabryce w zakładach rozproszonych.", "Utrzymanie ruchu, serwis, liderzy zakładzie w zakładach rozproszonych."],
  "sol_5_when": ["Ekspert nie zawsze jest na miejscu, a czas reakcji na awarie jest krytyczny.", "Ekspert nie zawsze jest na miejscu.", "Ekspert nie zawsze jest na miejscu, a czas reakcji na awarie jest krytyczny."],
  "sol_5_what": ["Wsparcie ‘hands-free’ na smart-okularach / tablecie + kontekstowe instrukcje.", "Wsparcie ‘hands-free’ na smart-okularach / tablecie + kontekstowe instrukcje.", "Wsparcie ‘hands-free’ na smart-okularach / tablecie + kontekstowe instrukcje."],
  "sol_5_effect": ["Szybsze usuwanie awarii, mniej delegacji, lepsze bezpieczeństwo pracy.", "Szybsze usuwanie awarii, mniej delegacji, lepsze bezpieczeństwo pracy.", "Szybsze usuwanie awarii, mniej delegacji, lepsze bezpieczeństwo pracy."],
  "sol_5_diff": ["Nastawienie na prostotę użycia i szybki start na produkcji.", "Nastawienie na prostotę użycia i szybki start na hali.", "Nastawienie na prostotę użycia i szybki start w operacjach."],
  "sol_title_6": ["Matryca kompetencji oparta o zadania", "Matryca Kompetencji", "Zarządzanie Umiejętnościami"],
  "sol_6_forWho": ["Kierownicy produkcji, HR/L&D, liderzy zespołów.", "Kierownicy fabryce, HR/L&D, liderzy zespołów.", "Kierownicy zakładzie, HR/L&D, liderzy zespołów."],
  "sol_6_when": ["Brakuje obiektywnego obrazu kompetencji i trudno obsadzać zmiany oraz planować szkolenia.", "Brakuje obiektywnego obrazu kompetencji i trudno obsadzać zmiany oraz planować szkolenia.", "Brakuje obiektywnego obrazu kompetencji i trudno obsadzać zmiany oraz planować szkolenia."],
  "sol_6_what": ["Panel do mapowania kompetencji do zadań + raporty i widok luk kompetencyjnych.", "Panel do mapowania kompetencji do zadań + raporty i widok luk kompetencyjnych.", "Panel do mapowania kompetencji do zadań + raporty i widok luk kompetencyjnych."],
  "sol_6_effect": ["Lepsze przydziały, mniej ryzyka jakości, czytelny plan rozwoju.", "Lepsze przydziały, mniej ryzyka jakości, czytelny plan rozwoju.", "Lepsze przydziały, mniej ryzyka jakości, czytelny plan rozwoju."],
  "sol_6_diff": ["Kompetencje liczone ‘od zadań’, nie od deklaracji.", "Kompetencje liczone ‘od zadań’.", "Kompetencje liczone ‘od zadań’, nie od deklaracji."],
  "sol_title_7": ["Automatyzacja kontroli jakości (Computer Vision)", "Automatyczna Kontrola Jakości", "Wizyjna Inspekcja"],
  "sol_7_forWho": ["Quality Manager, działy jakości, linie o wysokich wymaganiach zgodności (np. GMP).", "Quality Manager, działy jakości, linie o wysokich wymaganiach zgodności (np.", "Quality Manager, działy jakości, linie o wysokich wymaganiach zgodności (np. GMP)."],
  "sol_7_when": ["Kontrola jakości jest manualna, kosztowna i generuje reklamacje.", "Kontrola jakości jest manualna.", "Kontrola jakości jest manualna, kosztowna i generuje reklamacje."],
  "sol_7_what": ["Automatyczną inspekcję wizyjną + alerty i raportowanie odchyleń.", "Automatyczną inspekcję wizyjną + alerty i raportowanie odchyleń.", "Automatyczną inspekcję wizyjną + alerty i raportowanie odchyleń."],
  "sol_7_effect": ["Mniej reklamacji, stabilniejsza jakość, oszczędność czasu kontroli.", "Mniej reklamacji, stabilniejsza jakość, oszczędność czasu kontroli.", "Mniej reklamacji, stabilniejsza jakość, oszczędność czasu kontroli."],
  "sol_7_diff": ["Łączymy wiedzę branżową z praktyką wdrożeń computer vision.", "Integrujemy wiedzę operacyjną branżową z praktyką wdrożeń computer vision.", "Spajamy know-how branżową z praktyką wdrożeń computer vision."],
  "news_heading": ["Aktualności i Case Studies", "Blog i Wdrożenia", "Co nowego u nas?", "Baza wiedzy"],
  "news_badge": ["Nowość", "New", "Hot", "Ważne"],
  "news_cat_1": ["AKTUALNOŚCI", "NEWS", "INFORMACJE"],
  "news_cat_2": ["CASE STUDY", "WDROŻENIA", "SUKCESY"],
  "news_cat_3": ["BLOG", "ARTYKUŁ", "WIEDZA"],
  "news_date_1": ["June 10, 2024", "10 Czerwca 2024", "10.06.2024"],
  "news_date_2": ["May 22, 2024", "22 Maja 2024", "22.05.2024"],
  "news_date_3": ["April 15, 2024", "15 Kwietnia 2024", "15.04.2024"],
  "news_title_1": ["Apzumi Spatial nawiązało współpracę z DigiLens ARGO™", "Partnerstwo z DigiLens ARGO™", "Nowy partner technologiczny: DigiLens"],
  "news_title_2": ["Optymalizacja procesów logistycznych dla branży automotive", "Sukces w branży Automotive", "Logistyka 4.0 w praktyce"],
  "news_title_3": ["Jak zabezpieczyć dane w erze Przemysłu 4.0?", "Cyberbezpieczeństwo w IT/OT", "Ochrona danych w fabryce"],
  "testim_label": ["Rekomendacje", "Opinie Klientów", "Co mówią o nas", "Zaufali nam"],
  "testim_quote": ["W ramach projektu AR Container Planning utworzyliśmy bibliotekę opakowań i części... przenosi nas w inny wymiar planowania", "Współpraca z Apzumi pozwoliła nam zoptymalizować procesy magazynowe o 30%.", "Profesjonalne podejście i zrozumienie specyfiki branży automotive."],
  "testim_author": ["Tomasz Rudalski", "T. Rudalski", "Kierownik Projektu"],
  "testim_role": ["Projekty Logistyczne Września, Volkswagen", "VW Poznań", "Volkswagen Group Polska"],
  "contact_heading": ["Porozmawiajmy o szczegółach", "Skontaktuj się z nami", "Umów bezpłatną konsultację"],
  "contact_btn": ["Wyślij - odpowiemy", "Prześlij wiadomość", "Napisz do nas", "Skontaktuj się"],
  "footer_address_1": ["APZUMI Sp. z o.o. spółka komandytowa", "APZUMI Sp. z o.o. spółka komandytowa", "APZUMI Sp. z o.o. spółka komandytowa"],
  "footer_address_2": ["ul. Feliksa Nowowiejskiego 5", "ul. Feliksa Nowowiejskiego 5", "ul. Feliksa Nowowiejskiego 5"],
  "footer_address_3": ["61-731 Poznań", "61-731 Poznań", "61-731 Poznań"],
  "footer_contact": ["contact@apzumi.com", "biuro@apzumi.com", "contact@apzumi.com"],
  "footer_copyright": ["© 2024 Apzumi. All rights reserved.", "© 2024 Apzumi. Wszelkie prawa zastrzeżone.", "© 2024 Apzumi. All rights reserved."],
  "sol_page_hero_title": ["Rozwiązania Apzumi Spatial", "Produkty IT/OT", "Platforma Apzumi"],
  "sol_page_hero_title_suffix": ["dla produkcji", "dla przemysłu", "dla fabryk"],
  "sol_page_hero_lead": ["Jedna platforma, która łączy ludzi, procedury i wiedzę w jednym workflow — wspierana przez AI i Spatial Computing.", "Jedna platforma, która łączy ludzi, procedury i wiedzę w jednym workflow.", "Jedna platforma, która łączy ludzi, instrukcje i wiedzę operacyjną w jednym środowisku pracy — wspierana przez AI i Spatial Computing."],
  "sol_page_hero_sublead": ["Wybierz gotowe rozwiązanie dla swojego obszaru i zobacz, jak szybko dowozimy efekt: od pilota do skali.", "Wybierz gotowe rozwiązanie dla swojego obszaru i zobacz.", "Dobierz gotowe rozwiązanie dla swojego obszaru i zobacz, jak szybko dowozimy efekt: od pilota do skali."],
  "sol_page_hero_cta_demo": ["Umów demo", "Zamów prezentację", "Skontaktuj się"],
  "sol_page_hero_cta_cases": ["Zobacz case studies", "Realizacje", "Klienci"],
  "sol_page_filter_label": ["Wybierz obszar:", "Filtruj wg obszaru:", "Kategoria:"],
  "sol_filter_all": ["Wszystkie", "Wszystkie", "Wszystkie"],
  "sol_filter_production": ["Produkcja", "Produkcja", "Produkcja"],
  "sol_filter_maintenance": ["Utrzymanie ruchu", "Utrzymanie ruchu", "Utrzymanie ruchu"],
  "sol_filter_hr": ["HR & Kompetencje", "HR & Kompetencje", "HR & Kompetencje"],
  "sol_filter_quality": ["Jakość", "Jakość", "Jakość"],
  "sol_grid_heading": ["Wybierz obszar i dopasuj rozwiązanie", "Dobierz obszar i dopasuj rozwiązanie", "Znajdź obszar i dopasuj rozwiązanie"],
  "sol_grid_desc": ["Jeśli masz konkretny problem — wybierz rozwiązanie. Jeśli dopiero zaczynasz — przejdź do ‘Usług’.", "Jeśli masz konkretny problem — wybierz rozwiązanie.", "Jeśli masz konkretny problem — wybierz rozwiązanie. Jeśli dopiero zaczynasz — przejdź do ‘Usług’."],
  "sol_grid_disclaimer": ["Wartości efektów są orientacyjne — zależą od procesu, danych i warunków wdrożenia.", "Wartości efektów są orientacyjne.", "Wartości efektów są orientacyjne — zależą od procesu, danych i warunków wdrożenia."],
  "sol_grid_rec_label": ["Rekomendowane dla Ciebie", "Polecane", "Twój wybór"],
  "sol_grid_effects_label": ["Potencjalne efekty", "Korzyści", "ROI"],
  "sol_grid_btn_details": ["Zobacz szczegóły", "Zobacz szczegóły", "Zobacz szczegóły"],
  "sol_item_proc_title": ["Zdigitalizowane procedury dla produkcji", "Cyfrowe Instrukcje", "Digital Workflow"],
  "sol_item_proc_val": ["Zamień papier i rozproszone pliki w ustandaryzowane procedury krok-po-kroku z asystentem AI.", "Zamień papier i rozproszone pliki w ustandaryzowane instrukcje krok-po-kroku z asystentem AI.", "Zamień papier i rozproszone pliki w ustandaryzowane standardy krok-po-kroku z asystentem AI."],
  "sol_item_proc_trig": ["Awaria i długi przestój, bo zabrakło kompetentnej osoby lub szybkiego dostępu do wiedzy.", "Awaria i długi przestój, bo zabrakło kompetentnej osoby lub szybkiego dostępu do wiedzy.", "Awaria i długi przestój, bo zabrakło kompetentnej osoby lub szybkiego dostępu do wiedzy."],
  "sol_item_proc_btn": ["Porozmawiajmy o procedurach w Twojej fabryce", "Umów rozmowę o procedurach w Twojej fabryce", "Skontaktuj się o procedurach w Twojej fabryce"],
  "sol_item_remote_title": ["Audio-wizualne wsparcie dla pracowników (Remote Assist)", "Zdalny Ekspert", "Smart Glasses Support"],
  "sol_item_remote_val": ["Wolne ręce, szybka diagnoza i zdalna asysta eksperta — na smart okularach, z automatyczną transkrypcją i bazą wiedzy.", "Wolne ręce, szybka diagnoza i zdalna asysta eksperta.", "Wolne ręce, szybka diagnoza i zdalna asysta eksperta — na smart okularach, z automatyczną transkrypcją i bazą wiedzy."],
  "sol_item_remote_trig": ["Potrzebujesz natychmiastowego wsparcia przy awarii bez czekania na przyjazd serwisu.", "Potrzebujesz natychmiastowego wsparcia przy awarii bez czekania na przyjazd serwisu.", "Potrzebujesz natychmiastowego wsparcia przy awarii bez czekania na przyjazd serwisu."],
  "sol_item_remote_btn": ["Umów demo Remote Assist", "Zobacz demo Remote Assist", "Umów prezentację Remote Assist"],
  "sol_item_skills_title": ["Matryca kompetencji i alokacja zadań (Skills Matrix + AI)", "Matryca kompetencji i alokacja zadań (Skills Matrix + AI)", "Matryca kompetencji i alokacja zadań (Skills Matrix + AI)"],
  "sol_item_skills_val": ["Obiektywna matryca kompetencji budowana na podstawie realnie wykonanych zadań — z podpowiedziami i automatycznym przydziałem.", "Obiektywna matryca kompetencji budowana na podstawie realnie wykonanych zadań.", "Obiektywna matryca kompetencji budowana na podstawie realnie wykonanych zadań — z podpowiedziami i automatycznym przydziałem."],
  "sol_item_skills_trig": ["Harmonogramy i przydziały robione ręcznie, na subiektywnych ocenach.", "Harmonogramy i przydziały robione ręcznie.", "Harmonogramy i przydziały robione ręcznie, na subiektywnych ocenach."],
  "sol_item_skills_btn": ["Zobacz, jak działa Skills Matrix", "Sprawdź, jak działa Skills Matrix", "Poznaj, jak działa Skills Matrix"],
  "sol_item_cv_title": ["Automatyzacja kontroli jakości (Computer Vision)", "Automatyzacja kontroli jakości (Computer Vision)", "Automatyzacja kontroli jakości (Computer Vision)"],
  "sol_item_cv_val": ["Wykrywanie błędów i zanieczyszczeń na linii w czasie rzeczywistym — alarm wizualny i dźwiękowy + monitoring dla QA.", "Wykrywanie błędów i zanieczyszczeń na linii w czasie rzeczywistym.", "Wykrywanie błędów i zanieczyszczeń na linii w czasie rzeczywistym — alarm wizualny i dźwiękowy + monitoring dla QA."],
  "sol_item_cv_trig": ["Mimo double-check nadal trafiają się pozostałości — ryzyko reklamacji i kosztów.", "Mimo double-check nadal trafiają się pozostałości.", "Mimo double-check nadal trafiają się pozostałości — ryzyko reklamacji i kosztów."],
  "sol_item_cv_btn": ["Porozmawiajmy o Computer Vision", "Umów rozmowę o Computer Vision", "Skontaktuj się o Computer Vision"],
  "sol_tab_problem": ["Problem", "Wyzwanie", "Sytuacja"],
  "sol_tab_how": ["Jak działa", "Jak to działa", "Mechanizm"],
  "sol_tab_what": ["Co dostajesz", "Zakres", "Rezultat"],
  "sol_tab_who": ["Dla kogo", "Adresaci", "Role"],
  "sol_plat_heading": ["Jedna, zintegrowana platforma zamiast trzech narzędzi", "Jedna, zintegrowana platforma zamiast trzech narzędzi", "Jedna, zintegrowana platforma zamiast trzech narzędzi"],
  "sol_plat_desc": ["Procedury + zdalne wsparcie + baza wiedzy + AI Agent + raportowanie. To samo środowisko, te same dane, jeden workflow.", "Procedury + zdalne wsparcie + baza wiedzy + AI Agent + raportowanie.", "Procedury + zdalne wsparcie + baza wiedzy + AI Agent + raportowanie. To samo środowisko, te same dane, jeden workflow."],
  "sol_plat_item_1": ["Baza wiedzy", "Repozytorium wiedzy", "Centrum wiedzy"],
  "sol_plat_sub_1": ["DTR, manuale, wideo", "DTR, manuale, wideo", "DTR, manuale, wideo"],
  "sol_plat_item_2": ["AI Agent", "Asystent AI", "Agent AI"],
  "sol_plat_sub_2": ["Głos / Tekst", "Głos / Tekst", "Głos / Tekst"],
  "sol_plat_item_3": ["Procedury", "Instrukcje", "Standardy pracy"],
  "sol_plat_sub_3": ["Krok-po-kroku", "Krok-po-kroku", "Krok-po-kroku"],
  "sol_plat_item_4": ["Remote Assist", "Remote Assist", "Remote Assist"],
  "sol_plat_sub_4": ["Smart Glasses", "Smart Glasses", "Smart Glasses"],
  "sol_plat_item_5": ["Raporty", "Raportowanie", "Zestawienia"],
  "sol_plat_sub_5": ["Excel / PDF", "Excel / PDF", "Excel / PDF"],
  "sol_plat_item_6": ["Integracje", "Połączenia systemów", "Integracja IT/OT"],
  "sol_plat_sub_6": ["ERP / MES / CMMS", "ERP / MES / CMMS", "ERP / MES / CMMS"],
  "sol_plat_note": ["Dopasowujemy architekturę do polityki IT: możemy uruchomić model po stronie klienta (on-prem) albo integrować się z istniejącym LLM/RAG.", "Dopasowujemy architekturę do polityki IT: możemy uruchomić model po stronie klienta (on-prem) albo integrować się z istniejącym LLM/RAG.", "Dopasowujemy architekturę do polityki IT: możemy uruchomić model po stronie klienta (on-prem) albo integrować się z istniejącym LLM/RAG."],
  "sol_proc_heading": ["Od rozpoznania do skali — w 3 prostych krokach", "Od rozpoznania do skali.", "Od rozpoznania do skali — w 3 prostych krokach"],
  "sol_proc_step1_title": ["Rozpoznanie i doprecyzowanie celu", "Rozpoznanie i doprecyzowanie celu", "Rozpoznanie i doprecyzowanie celu"],
  "sol_proc_step1_desc": ["Mapujemy proces, potrzeby i ograniczenia. Ustalamy KPI oraz to, co ma powstać.", "Mapujemy proces, potrzeby i ograniczenia.", "Mapujemy proces, potrzeby i ograniczenia. Ustalamy KPI oraz to, co ma powstać."],
  "sol_proc_step2_title": ["Pilot / PoC-first", "Pilot / PoC-first", "Pilot / PoC-first"],
  "sol_proc_step2_desc": ["Budujemy i uruchamiamy pilota na realnym fragmencie procesu, żeby zweryfikować założenia i policzyć efekt.", "Budujemy i uruchamiamy pilota na realnym fragmencie procesu.", "Budujemy i uruchamiamy pilota na realnym fragmencie procesu, żeby zweryfikować założenia i policzyć efekt."],
  "sol_proc_step3_title": ["Skalowanie i utrzymanie efektu", "Skalowanie i utrzymanie efektu", "Skalowanie i utrzymanie efektu"],
  "sol_proc_step3_desc": ["Rozszerzamy rozwiązanie na kolejne obszary, monitorujemy wyniki i optymalizujemy.", "Rozszerzamy rozwiązanie na kolejne obszary.", "Rozszerzamy rozwiązanie na kolejne obszary, monitorujemy wyniki i optymalizujemy."],
  "sol_cases_heading": ["Sprawdzone w środowisku produkcyjnym", "Sprawdzone w środowisku produkcyjnym", "Sprawdzone w środowisku produkcyjnym"],
  "sol_case_label": ["Case Study", "Case Study", "Case Study"],
  "sol_case_link": ["Czytaj więcej", "Czytaj więcej", "Czytaj więcej"],
  "sol_case_1": ["Automotive: optymalizacja pracy na linii", "Automotive: optymalizacja pracy na linii", "Automotive: optymalizacja pracy na linii"],
  "sol_case_2": ["Utrzymanie ruchu: skrócenie czasu diagnozy awarii", "Utrzymanie ruchu: skrócenie czasu diagnozy awarii", "Utrzymanie ruchu: skrócenie czasu diagnozy awarii"],
  "sol_case_3": ["Quality/GMP: automatyzacja kontroli czystości linii", "Quality/GMP: automatyzacja kontroli czystości linii", "Quality/GMP: automatyzacja kontroli czystości linii"],
  "sol_form_heading": ["Masz konkretny problem na produkcji?", "Masz konkretny problem na hali?", "Masz konkretny problem w operacjach?"],
  "sol_form_desc": ["Opowiedz nam w 15 minut, co chcesz poprawić. Zaproponujemy najlepsze rozwiązanie Apzumi Spatial i plan pilota.", "Opowiedz nam w 15 minut, co chcesz poprawić.", "Opowiedz nam w 15 minut, co chcesz poprawić. Zaproponujemy najlepsze rozwiązanie Apzumi Spatial i plan pilota."],
  "sol_form_ph_name": ["Imię i nazwisko", "Imię i nazwisko", "Imię i nazwisko"],
  "sol_form_ph_company": ["Firma", "Firma", "Firma"],
  "sol_form_ph_email": ["E-mail służbowy", "E-mail służbowy", "E-mail służbowy"],
  "sol_form_ph_area": ["Wybierz obszar...", "Wybierz obszar...", "Wybierz obszar..."],
  "sol_form_ph_msg": ["Wiadomość (opcjonalnie)", "Wiadomość (opcjonalnie)", "Wiadomość (opcjonalnie)"],
  "sol_form_consent": ["Wyrażam zgodę na przetwarzanie danych osobowych w celu kontaktu.", "Wyrażam zgodę na przetwarzanie danych osobowych w celu kontaktu.", "Wyrażam zgodę na przetwarzanie danych osobowych w celu kontaktu."],
  "sol_form_btn": ["Porozmawiajmy", "Porozmawiajmy", "Porozmawiajmy"],
  "sol_form_link": ["Poproś o demo", "Zobacz demo", "Umów prezentację"],
  "serv_hero_title": ["Usługi Apzumi Spatial — od pomysłu do efektu na produkcji", "Usługi Apzumi Spatial.", "Usługi Apzumi Spatial — od pomysłu do efektu na hali"],
  "serv_hero_lead": ["Pomagamy przejść od potrzeby biznesowej do działającego pilota i skalowania. Bez zgadywania — z KPI, PoC-first i dopasowaniem do Twojej polityki IT.", "Pomagamy przejść od potrzeby biznesowej do działającego pilota i skalowania.", "Pomagamy przejść od potrzeby biznesowej do działającego pilota i skalowania. Bez zgadywania — z KPI, PoC-first i dopasowaniem do Twojej polityki IT."],
  "serv_hero_sublead": ["Jeśli dopiero zaczynasz — wybierz warsztat. Jeśli chcesz walidacji — prototyp. Jeśli potrzebujesz rozwiązania szytego na miarę — custom development.", "Jeśli dopiero zaczynasz — wybierz warsztat.", "Jeśli dopiero zaczynasz — wybierz warsztat. Jeśli chcesz walidacji — prototyp. Jeśli potrzebujesz rozwiązania szytego na miarę — custom development."],
  "serv_hero_cta_primary": ["Porozmawiajmy", "Porozmawiajmy", "Porozmawiajmy"],
  "serv_hero_cta_secondary": ["Zobacz gotowe rozwiązania", "Sprawdź gotowe rozwiązania", "Poznaj gotowe rozwiązania"],
  "serv_filter_title": ["Wybierz usługę dopasowaną do Twojej sytuacji", "Dobierz usługę dopasowaną do Twojej sytuacji", "Znajdź usługę dopasowaną do Twojej sytuacji"],
  "serv_filter_desc": ["W praktyce większość projektów zaczyna się od jednego z trzech scenariuszy poniżej.", "W praktyce większość projektów zaczyna się od jednego z trzech scenariuszy poniżej.", "W praktyce większość projektów zaczyna się od jednego z trzech scenariuszy poniżej."],
  "serv_filter_start": ["Start (nie wiem od czego zacząć)", "Start (nie wiem od czego zacząć)", "Start (nie wiem od czego zacząć)"],
  "serv_filter_valid": ["Walidacja (chcę policzyć ROI)", "Walidacja (chcę policzyć ROI)", "Walidacja (chcę policzyć ROI)"],
  "serv_filter_build": ["Budowa (potrzebuję rozwiązania)", "Budowa (potrzebuję rozwiązania)", "Budowa (potrzebuję rozwiązania)"],
  "serv_rec_label": ["Rekomendowana usługa", "Rekomendowana usługa", "Rekomendowana usługa"],
  "serv_card_btn": ["Zobacz szczegóły", "Zobacz szczegóły", "Zobacz szczegóły"],
  "serv_diff_label": ["Nasz wyróżnik (Differentiator)", "Nasz wyróżnik (Differentiator)", "Nasz wyróżnik (Differentiator)"],
  "serv_grid_note": ["Zaczynamy od najmniejszego sensownego zakresu, żeby szybko dowieźć wynik i dopiero potem skalować.", "Zaczynamy od najmniejszego sensownego zakresu.", "Zaczynamy od najmniejszego sensownego zakresu, żeby szybko dowieźć wynik i dopiero potem skalować."],
  "serv_item_workshop_title": ["AI Workshop", "AI Workshop", "AI Workshop"],
  "serv_item_workshop_val": ["Warsztat, który kończy się roadmapą i KPI — wybierasz use-case’y z realnym potencjałem ROI.", "Warsztat, który kończy się roadmapą i KPI.", "Warsztat, który kończy się roadmapą i KPI — wybierasz use-case’y z realnym potencjałem ROI."],
  "serv_item_workshop_trig": ["Czujesz presję związaną z Przemysłem 4.0, ale nie wiesz od czego zacząć. Chcesz przetestować AI w swoim biznesie.", "Czujesz presję związaną z Przemysłem 4.0, ale nie wiesz od czego zacząć.", "Czujesz presję związaną z Przemysłem 4.0, ale nie wiesz od czego zacząć. Chcesz przetestować AI w swoim biznesie."],
  "serv_item_workshop_btn": ["Umów warsztat", "Umów warsztat", "Umów warsztat"],
  "serv_workshop_desc": ["Przeprowadzamy intensywne warsztaty, na których zderzamy Twoje wyzwania biznesowe z możliwościami technologii. Nasi eksperci dobierają use-cases z najwyższym potencjałem zwrotu z inwestycji (ROI).", "Przeprowadzamy intensywne warsztaty, na których zderzamy Twoje wyzwania biznesowe z możliwościami technologii.", "Przeprowadzamy intensywne warsztaty, na których zderzamy Twoje wyzwania biznesowe z możliwościami technologii. Nasi eksperci dobierają use-cases z najwyższym potencjałem zwrotu z inwestycji (ROI)."],
  "serv_workshop_forWho": ["Średnie przedsiębiorstwa produkcyjne, logistyczne, usługowe i retail. CEO, COO, IT Managerowie.", "Średnie przedsiębiorstwa produkcyjne, logistyczne, usługowe i retail.", "Średnie przedsiębiorstwa produkcyjne, logistyczne, usługowe i retail. CEO, COO, IT Managerowie."],
  "serv_workshop_when": ["Czujesz presję na automatyzację/AI, chcesz zwiększyć możliwości optymalizacji wewnętrznych procesów, ale obawiasz się ryzyka i 'przepalenia' budżetu na niesprawdzone pomysły.", "Czujesz presję na automatyzację/AI.", "Czujesz presję na automatyzację/AI, chcesz zwiększyć możliwości optymalizacji wewnętrznych procesów, ale obawiasz się ryzyka i 'przepalenia' budżetu na niesprawdzone pomysły."],
  "serv_workshop_what": ["Wytwarzamy 'Business Needs & Vision'. Otrzymujesz udokumentowane KPI oraz Raport po AI Workshop z podsumowaniem, rekomendacjami wdrożeniowymi i roadmapą.", "Wytwarzamy 'Business Needs & Vision'.", "Wytwarzamy 'Business Needs & Vision'. Otrzymujesz udokumentowane KPI oraz Raport po AI Workshop z podsumowaniem, rekomendacjami wdrożeniowymi i roadmapą."],
  "serv_workshop_effect": ["Celem warsztatów jest zidentyfikowanie w Twojej firmie procesów i pomysłów, które mogą przynieść praktyczne korzyści. Otrzymujesz profesjonalnie opracowany raport stanowiący gotowy plan działania (Roadmap).", "Celem warsztatów jest zidentyfikowanie w Twojej firmie procesów i pomysłów, które mogą przynieść praktyczne korzyści.", "Celem warsztatów jest zidentyfikowanie w Twojej firmie procesów i pomysłów, które mogą przynieść praktyczne korzyści. Otrzymujesz profesjonalnie opracowany raport stanowiący gotowy plan działania (Roadmap)."],
  "serv_workshop_diff": ["Wykorzystujemy naszą autorską metodologię pozwalającą na szybkie (10 dni) i precyzyjne określenie najbardziej obiecujących obszarów, które przyniosą realne ROI (np. 95% wzrost efektywności w wybranych procesach).", "Wykorzystujemy naszą autorską metodologię pozwalającą na szybkie (10 dni) i precyzyjne określenie najbardziej obiecujących obszarów, które przyniosą realne ROI (np.", "Wykorzystujemy naszą autorską metodologię pozwalającą na szybkie (10 dni) i precyzyjne określenie najbardziej obiecujących obszarów, które przyniosą realne ROI (np. 95% wzrost efektywności w wybranych procesach)."],
  "serv_workshop_process": ["1. Analiza business needs & vision (Pre-work)\\n2. Warsztaty stacjonarne (Brainstorming & Filtering)\\n3. Weryfikacja techniczna i analiza wykonalności\\n4. Raport końcowy z roadmapą i estymacją.", "• Analiza business needs & vision (Pre-work)\\n• Warsztaty stacjonarne (Brainstorming & Filtering)\\n• Weryfikacja techniczna i analiza wykonalności\\n• Raport końcowy z roadmapą i estymacją.", "Krok 1: Analiza business needs & vision (Pre-work)\\nKrok 2: Warsztaty stacjonarne (Brainstorming & Filtering)\\nKrok 3: Weryfikacja techniczna i analiza wykonalności\\nKrok 4: Raport końcowy z roadmapą i estymacją."],
  "serv_workshop_artifacts": ["Raport Strategiczny, Lista Priorytetowych Use-Cases, Analiza ROI/TCO, Roadmapa Wdrożenia, Rekomendacje Architektoniczne.", "Raport Strategiczny, Lista Priorytetowych Use-Cases, Analiza ROI/TCO, Roadmapa Wdrożenia, Rekomendacje Architektoniczne.", "Raport Strategiczny, Lista Priorytetowych Use-Cases, Analiza ROI/TCO, Roadmapa Wdrożenia, Rekomendacje Architektoniczne."],
  "serv_item_proto_title": ["AI Prototyping & Product Discovery", "AI Prototyping & Product Discovery", "AI Prototyping & Product Discovery"],
  "serv_item_proto_val": ["Discovery + prototyp do testów z użytkownikami — zanim wejdziesz w pełne wdrożenie.", "Discovery + prototyp do testów z użytkownikami.", "Discovery + prototyp do testów z użytkownikami — zanim wejdziesz w pełne wdrożenie."],
  "serv_item_proto_trig": ["Chcesz zidentyfikować konkretne zastosowania, które przyniosą mierzalne ROI, a nie tylko innowację dla innowacji.", "Chcesz zidentyfikować konkretne zastosowania.", "Chcesz zidentyfikować konkretne zastosowania, które przyniosą mierzalne ROI, a nie tylko innowację dla innowacji."],
  "serv_item_proto_btn": ["Zróbmy prototyp", "Zróbmy prototyp", "Zróbmy prototyp"],
  "serv_proto_desc": ["Solution Discovery Product: Warsztaty i sprinty, które mają na celu zderzenie koncepcji aplikacji z rzeczywistością. Następnie nasz ekspert pomaga przygotować prototyp (PoC) w celu weryfikacji na produkcji.", "Solution Discovery Product: Warsztaty i sprinty, które mają na celu zderzenie koncepcji aplikacji z rzeczywistością.", "Solution Discovery Product: Warsztaty i sprinty, które mają na celu zderzenie koncepcji aplikacji z rzeczywistością. Następnie nasz ekspert pomaga przygotować prototyp (PoC) w celu weryfikacji na hali."],
  "serv_proto_forWho": ["Duże przedsiębiorstwa produkcyjne, logistyczne. IT Director, Head of Innovation, Transformation Manager, R&D Lead.", "Duże przedsiębiorstwa produkcyjne, logistyczne.", "Duże przedsiębiorstwa produkcyjne, logistyczne. IT Director, Head of Innovation, Transformation Manager, R&D Lead."],
  "serv_proto_when": ["Masz pomysł, ale potrzebujesz weryfikacji w realnym środowisku (na hali). Chcesz uniknąć dużych strat związanych z wdrożeniem systemu, którego nikt nie będzie używał.", "Masz pomysł, ale potrzebujesz weryfikacji w realnym środowisku (na hali).", "Masz pomysł, ale potrzebujesz weryfikacji w realnym środowisku (na hali). Chcesz uniknąć dużych strat związanych z wdrożeniem systemu, którego nikt nie będzie używał."],
  "serv_proto_what": ["Weryfikacja pomysłu: przygotowujemy prototyp (PoC) w 48h-5dni, dokumentację oraz przeprowadzamy testy z użytkownikami (User Testing) w warunkach operacyjnych.", "Weryfikacja pomysłu: przygotowujemy prototyp (PoC) w 48h-5dni.", "Weryfikacja pomysłu: przygotowujemy prototyp (PoC) w 48h-5dni, dokumentację oraz przeprowadzamy testy z użytkownikami (User Testing) w warunkach operacyjnych."],
  "serv_proto_effect": ["Stworzenie prototypu pozwala na przetestowanie pomysłu na wczesnym etapie. Oszczędność czasu i budżetu dzięki eliminacji błędnych założeń (Fail Fast). Decyzja o wdrożeniu oparta o twarde dane.", "Stworzenie prototypu pozwala na przetestowanie pomysłu na wczesnym etapie.", "Stworzenie prototypu pozwala na przetestowanie pomysłu na wczesnym etapie. Oszczędność czasu i budżetu dzięki eliminacji błędnych założeń (Fail Fast). Decyzja o wdrożeniu oparta o twarde dane."],
  "serv_proto_diff": ["Wiedza ekspercka z zakresu przemysłu i UX. Rozumienie problemów technologicznych i wyzwań specyficznych dla branży. Skupiamy się na biznesie i potrzebach realnych użytkowników (operatorów), nie tylko na technologii.", "Wiedza ekspercka z zakresu przemysłu i UX.", "Wiedza ekspercka z zakresu przemysłu i UX. Rozumienie problemów technologicznych i wyzwań specyficznych dla branży. Skupiamy się na biznesie i potrzebach realnych użytkowników (operatorów), nie tylko na technologii."],
  "serv_proto_process": ["1. Discovery Workshop\\n2. Rapid Prototyping (Low/High Fidelity)\\n3. User Testing na hali produkcyjnej\\n4. Feedback Loop & Iteracja\\n5. Final Report & Go/No-Go Decision.", "• Discovery Workshop\\n• Rapid Prototyping (Low/High Fidelity)\\n• User Testing na hali produkcyjnej\\n• Feedback Loop & Iteracja\\n• Final Report & Go/No-Go Decision.", "Krok 1: Discovery Workshop\\nKrok 2: Rapid Prototyping (Low/High Fidelity)\\nKrok 3: User Testing na hali produkcyjnej\\nKrok 4: Feedback Loop & Iteracja\\nKrok 5: Final Report & Go/No-Go Decision."],
  "serv_proto_artifacts": ["Klikalny prototyp (Figma/Web/Tablet), Raport z testów użyteczności (Video/Heatmaps), Backlog produktowy, Estymacja kosztów pełnego wdrożenia.", "Klikalny prototyp (Figma/Web/Tablet), Raport z testów użyteczności (Video/Heatmaps), Backlog produktowy, Estymacja kosztów pełnego wdrożenia.", "Klikalny prototyp (Figma/Web/Tablet), Raport z testów użyteczności (Video/Heatmaps), Backlog produktowy, Estymacja kosztów pełnego wdrożenia."],
  "serv_item_custom_title": ["Digitization & Custom Development", "Digitization & Custom Development", "Digitization & Custom Development"],
  "serv_item_custom_val": ["Dedykowane rozwiązanie, gdy gotowce nie pasują — integracje i dopasowanie do procesu.", "Dedykowane rozwiązanie, gdy gotowce nie pasują.", "Dedykowane rozwiązanie, gdy gotowce nie pasują — integracje i dopasowanie do procesu."],
  "serv_item_custom_trig": ["Masz problem, którego nie da się rozwiązać gotowym oprogramowaniem (np. predykcja awarii, specyficzny proces manualny, unikalne maszyny).", "Masz problem, którego nie da się rozwiązać gotowym oprogramowaniem (np.", "Masz problem, którego nie da się rozwiązać gotowym oprogramowaniem (np. predykcja awarii, specyficzny proces manualny, unikalne maszyny)."],
  "serv_item_custom_btn": ["Porozmawiajmy", "Porozmawiajmy", "Porozmawiajmy"],
  "serv_custom_desc": ["Zaczynamy od Solution Discovery Workshop w celu określenia Pain Points i priorytetów. Budujemy dedykowane oprogramowanie (web/mobile/AI/AR) idealnie dopasowane do Twojego procesu i zintegrowane z Twoim IT/OT.", "Zaczynamy od Solution Discovery Workshop w celu określenia Pain Points i priorytetów.", "Zaczynamy od Solution Discovery Workshop w celu określenia Pain Points i priorytetów. Budujemy dedykowane oprogramowanie (web/mobile/AI/AR) idealnie dopasowane do Twojego procesu i zintegrowane z Twoim IT/OT."],
  "serv_custom_forWho": ["Duże przedsiębiorstwa produkcyjne, logistyczne. CEO, Director, COO, Plant Manager, Digital Transformation Lead.", "Duże przedsiębiorstwa produkcyjne, logistyczne.", "Duże przedsiębiorstwa produkcyjne, logistyczne. CEO, Director, COO, Plant Manager, Digital Transformation Lead."],
  "serv_custom_when": ["Standardowe systemy (ERP/MES) nie wystarczają lub są zbyt sztywne. Masz specyficzny proces, który wymaga 'szytego na miarę' podejścia i głębokiej integracji.", "Standardowe systemy (ERP/MES) nie wystarczają lub są zbyt sztywne.", "Standardowe systemy (ERP/MES) nie wystarczają lub są zbyt sztywne. Masz specyficzny proces, który wymaga 'szytego na miarę' podejścia i głębokiej integracji."],
  "serv_custom_what": ["Custom Software Development: Przeanalizujemy, zaprojektujemy i wdrożymy systemy klasy Enterprise. Od backendu, przez mobile/web, aż po algorytmy AI i Computer Vision.", "Custom Software Development: Przeanalizujemy, zaprojektujemy i wdrożymy systemy klasy Enterprise.", "Custom Software Development: Przeanalizujemy, zaprojektujemy i wdrożymy systemy klasy Enterprise. Od backendu, przez mobile/web, aż po algorytmy AI i Computer Vision."],
  "serv_custom_effect": ["Udowodnienie wartości biznesowej AI na konkretnym, trudnym problemie. Stworzenie unikalnej przewagi technologicznej i pełna własność intelektualna (IP) rozwiązania, co buduje wartość firmy.", "Udowodnienie wartości biznesowej AI na konkretnym, trudnym problemie.", "Udowodnienie wartości biznesowej AI na konkretnym, trudnym problemie. Stworzenie unikalnej przewagi technologicznej i pełna własność intelektualna (IP) rozwiązania, co buduje wartość firmy."],
  "serv_custom_diff": ["Podejście PoC-first: nie inwestujesz w pełne wdrożenie, dopóki nie zobaczysz działającego fragmentu (MVP). Rozumiemy integracje IT/OT i wiemy jak bezpiecznie podłączyć się do systemów i maszyn (Siemens, Rockwell, SAP).", "Podejście PoC-first: nie inwestujesz w pełne wdrożenie, dopóki nie zobaczysz działającego fragmentu (MVP).", "Podejście PoC-first: nie inwestujesz w pełne wdrożenie, dopóki nie zobaczysz działającego fragmentu (MVP). Rozumiemy integracje IT/OT i wiemy jak bezpiecznie podłączyć się do systemów i maszyn (Siemens, Rockwell, SAP)."],
  "serv_custom_process": ["1. Solution Discovery\\n2. Architecture Design & Security\\n3. Agile Development (Sprints)\\n4. Integration & UAT Testing\\n5. Deployment & SLA Maintenance.", "• Solution Discovery\\n• Architecture Design & Security\\n• Agile Development (Sprints)\\n• Integration & UAT Testing\\n• Deployment & SLA Maintenance.", "Krok 1: Solution Discovery\\nKrok 2: Architecture Design & Security\\nKrok 3: Agile Development (Sprints)\\nKrok 4: Integration & UAT Testing\\nKrok 5: Deployment & SLA Maintenance."],
  "serv_custom_artifacts": ["Kod źródłowy (Pełne IP), Dokumentacja techniczna i API, Działająca aplikacja (Web/Mobile), Instrukcje użytkownika, Plan utrzymania (SLA) i rozwoju.", "Kod źródłowy (Pełne IP), Dokumentacja techniczna i API, Działająca aplikacja (Web/Mobile), Instrukcje użytkownika, Plan utrzymania (SLA) i rozwoju.", "Kod źródłowy (Pełne IP), Dokumentacja techniczna i API, Działająca aplikacja (Web/Mobile), Instrukcje użytkownika, Plan utrzymania (SLA) i rozwoju."],
  "serv_tab_process": ["Jak to robimy (Proces)", "Jak to robimy (Proces)", "Jak to robimy (Proces)"],
  "serv_tab_arts": ["Co dostajesz (Artefakty)", "Co dostajesz (Artefakty)", "Co dostajesz (Artefakty)"],
  "serv_tab_val": ["Wartość biznesowa", "Wartość biznesowa", "Wartość biznesowa"],
  "serv_tab_sec": ["Bezpieczeństwo & Tech", "Bezpieczeństwo & Tech", "Bezpieczeństwo & Tech"],
  "serv_tab_cta": ["CTA", "CTA", "CTA"],
  "serv_label_for_who": ["Dla kogo", "Adresaci", "Role"],
  "serv_label_when": ["Sytuacja Klienta", "Sytuacja Klienta", "Sytuacja Klienta"],
  "serv_label_what": ["Co robimy - Operations", "Co robimy - Operations", "Co robimy - Operations"],
  "serv_label_effect": ["Cel i Efekt", "Cel i Efekt", "Cel i Efekt"],
  "serv_comp_heading": ["Kiedy usługa, a kiedy gotowe rozwiązanie?", "Kiedy usługa, a kiedy gotowe rozwiązanie?", "Kiedy usługa, a kiedy gotowe rozwiązanie?"],
  "serv_comp_serv_title": ["Wybierz USŁUGĘ, gdy:", "Dobierz USŁUGĘ, gdy:", "Znajdź USŁUGĘ, gdy:"],
  "serv_comp_serv_desc": ["nie masz jeszcze doprecyzowanego problemu, chcesz roadmapy, potrzebujesz walidacji ROI lub Twój proces jest bardzo specyficzny.", "nie masz jeszcze doprecyzowanego problemu.", "nie masz jeszcze doprecyzowanego problemu, chcesz roadmapy, potrzebujesz walidacji ROI lub Twój proces jest bardzo specyficzny."],
  "serv_comp_sol_title": ["Wybierz ROZWIĄZANIE, gdy:", "Dobierz ROZWIĄZANIE, gdy:", "Znajdź ROZWIĄZANIE, gdy:"],
  "serv_comp_sol_desc": ["masz konkretny obszar (procedury/UR/kompetencje/jakość) i chcesz szybki start (wdrożenie w tygodnie, nie miesiące).", "masz konkretny obszar (procedury/UR/kompetencje/jakość) i chcesz szybki start (wdrożenie w tygodnie.", "masz konkretny obszar (instrukcje/UR/kompetencje/jakość) i chcesz szybki start (wdrożenie w tygodnie, nie miesiące)."],
  "serv_comp_link": ["Przejdź do Rozwiązań", "Przejdź do Rozwiązań", "Przejdź do Rozwiązań"],
  "serv_faq_q1": ["Ile trwa start?", "Ile trwa start?", "Ile trwa start?"],
  "serv_faq_a1": ["Zależy od zakresu — zaczynamy od najmniejszego sensownego pilota (MVP), żeby szybko (nawet w 4-6 tygodni) policzyć efekt.", "Zależy od zakresu — zaczynamy od najmniejszego sensownego pilota (MVP).", "Zależy od zakresu — zaczynamy od najmniejszego sensownego pilota (MVP), żeby szybko (nawet w 4-6 tygodni) policzyć efekt."],
  "serv_faq_q2": ["Czy można on-premise?", "Czy można on-premise?", "Czy można on-premise?"],
  "serv_faq_a2": ["Tak — dopasowujemy wariant do polityki IT i danych. Możemy wdrażać w chmurze prywatnej lub na infrastrukturze klienta.", "Tak — dopasowujemy wariant do polityki IT i danych.", "Tak — dopasowujemy wariant do polityki IT i danych. Możemy wdrażać w chmurze prywatnej lub na infrastrukturze klienta."],
  "serv_faq_q3": ["Czy muszę mieć smart okulary?", "Czy muszę mieć smart okulary?", "Czy muszę mieć smart okulary?"],
  "serv_faq_a3": ["Nie — dobieramy hardware do procesu. Większość naszych rozwiązań działa na tabletach, smartfonach i komputerach PC. Okulary to opcja.", "Nie — dobieramy hardware do procesu.", "Nie — dobieramy hardware do procesu. Większość naszych rozwiązań działa na tabletach, smartfonach i komputerach PC. Okulary to opcja."],
  "serv_faq_q4": ["Jak mierzycie sukces?", "Jak mierzycie sukces?", "Jak mierzycie sukces?"],
  "serv_faq_a4": ["Ustalamy KPI na starcie warsztatów (np. redukcja czasu przestoju, liczba błędów, czas onboardingu). Rozliczamy się z dowiezienia wartości.", "Ustalamy KPI na starcie warsztatów (np.", "Ustalamy KPI na starcie warsztatów (np. redukcja czasu przestoju, liczba błędów, czas onboardingu). Rozliczamy się z dowiezienia wartości."],
  "serv_form_heading": ["Powiedz nam, co chcesz usprawnić — wrócimy z propozycją usługi i planem pilota", "Powiedz nam, co chcesz usprawnić.", "Powiedz nam, co chcesz usprawnić — wrócimy z propozycją usługi i planem pilota"],
  "serv_form_desc": ["W 15 minut zbierzemy kontekst i zaproponujemy najlepszą ścieżkę: warsztat, prototyp lub PoC-first.", "W 15 minut zbierzemy kontekst i zaproponujemy najlepszą ścieżkę: warsztat.", "W 15 minut zbierzemy kontekst i zaproponujemy najlepszą ścieżkę: warsztat, prototyp lub PoC-first."],
  "serv_form_btn": ["Porozmawiajmy", "Porozmawiajmy", "Porozmawiajmy"],
  "serv_form_link": ["Poproś o demo", "Zobacz demo", "Umów prezentację"],
};
